---
- name: Creating a simple playbook
  hosts: all
  tasks:
  -  name: IIS Service installed
     win_feature:
       name: Web-Server
       state: present
  - name: IIS Service started
    win_service:
       name: W3Svc
       state: started
  - name: Website index.html created
    win_copy:
      content: "Hello World!"
      dest: C:\Inetpub\wwwroot\index.html

- name: This is second playbook
  hosts: all
  tasks: 
      - name: Creating a directory
        win_file:
              path: c:\custom_share
              state: directory
      - name: Enabling the sharing
        win_share:
          name: windows_share
          description: this is a custom share
          path: c:\custom_share
          full: Administrator
          state: present
      - name: Copying some custom content
        win_copy:
            content: "This is a shared content"
            dest: C:\\Custom_share\\shared.txt
...